name: android_remote_control_client
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  control_pad: ^1.1.1+1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
